name: Deploy to Netcup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Code auschecken
      uses: actions/checkout@v4
      
    - name: Node.js einrichten
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Abhängigkeiten installieren
      run: npm install

    - name: Projekt bauen (Build)
      run: npm run build

    - name: FTP-Upload zu Netcup
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /httpdocs/
